// Gary
// Copyright 2017 Keiran King

// LICENSE --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// (https://www.apache.org/licenses/LICENSE-2.0)

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// CONSTANTS ------------------------------------------------------------------
const CATEGORIES = [
  "3-letter words",
  "4-letter words",
  "9-letter words",
  "A boy's name",
  "A gender-neutral name",
  "A girl's name",
  "A name in your family",
  "Acronyms",
  "Adjectives",
  "Adult toys",
  "Airlines",
  "Animal noises",
  "Animals",
  "Animals in books or movies",
  "Appliances",
  "Articles of clothing",
  "Athletes",
  "Authors",
  "Awards/ceremonies",
  "Baby foods",
  "Backyard items",
  "Bad habits",
  "Birds",
  "Board games",
  "Bodies of water",
  "Book titles",
  "Breakfast foods",
  "Capitals",
  "Card games",
  "Car parts",
  "Cars",
  "Cartoon characters",
  "Categories in this game",
  "Celebrities",
  "Celebs half or twice your age",
  "Cereals",
  "Children's books",
  "Christmas decorations",
  "Christmas songs",
  "Clothing brands",
  "College majors",
  "Colleges/universities",
  "Colors",
  "Companies",
  "Composers",
  "Computer parts",
  "Computer programs",
  "Cooking utensils",
  "Corporate-speak",
  "Cosmetics/toiletries",
  "Countries",
  "Crimes",
  "Crunchy foods",
  "Currencies",
  "Curse words",
  "Dairy products",
  "Desk jobs",
  "Desserts",
  "Diet foods",
  "Disasters",
  "Diseases",
  "Disgraced celebrities",
  "Documents",
  "Electronic gadgets",
  "Elements on the periodic table",
  "Emotions",
  "Excuses for being late",
  "Fabrics",
  "Famous buildings",
  "Famous criminals",
  "Famous duos and trios",
  "Famous people who aren't white",
  "Famous quotes",
  "Famous women",
  "Farm animals",
  "Fads in fashion",
  "Father's Day gifts/activities",
  "Fetishes",
  "Fictional characters",
  "Fish",
  "Flowers",
  "Food/drink that is green",
  "Food/drink that is red",
  "Food/drink that is yellow",
  "Foods you bake",
  "Foods you eat raw",
  "Footwear",
  "Foreign cities",
  "Foreign words used in English",
  "Fruits",
  "Furniture",
  "Games",
  "Game terms",
  "Gases",
  "Gifts/presents",
  "Gods and deities",
  "Grammar terms",
  "Headwear",
  "Heroes",
  "Historical figures",
  "Historic events",
  "Hobbies",
  "Holiday activities",
  "Holidays",
  "Holy words",
  "Homophone sets (eg bare, bear)",
  "Honeymoon spots",
  "Hotels",
  "Household chores",
  "Hyphenated words",
  "Ice cream flavors",
  "Idioms and proverbs",
  "Indoor sports",
  "Inedible items that go inside you",
  "Infrastructure",
  "Injuries",
  "Insects",
  "Internet celebrities",
  "Internet lingo",
  "Invisible things",
  "Items in a car trunk",
  "Items in a catalog",
  "Items in a gift basket",
  "Items in a glove compartment",
  "Items in a kitchen",
  "Items in a locker",
  "Items in a Neanderthal camp",
  "Items in a nighttable",
  "Items in a refrigerator",
  "Items in a suitcase",
  "Items in a vending machine",
  "Items in this room",
  "Items in your purse/wallet",
  "Items you save up to buy",
  "Items you take on a trip",
  "Jewelry",
  "Junk food",
  "Kinds of bags",
  "Kinds of buildings",
  "Kinds of candy",
  "Kinds of dances",
  "Kinds of soup",
  "Languages",
  "Legal terms",
  "Leisure activities",
  "Famous LGBTQ people",
  "Liquors",
  "Magazines",
  "Manual labor jobs",
  "Math terms",
  "Mechanical objects",
  "Medical terms",
  "Medicines/drugs",
  "Menu items",
  "Microscopic things",
  "Movie stars",
  "Movie titles",
  "Musical groups",
  "Musical instruments",
  "Mythological characters",
  "Names in the news",
  "Names from Shakespeare",
  "Names used in songs",
  "Names in the Bible",
  "New Year's Eve words",
  "Nicknames",
  "Nocturnal animals",
  "Notorious people",
  "Objects made before 1900",
  "Obsolete things",
  "Occupations",
  "Offensive words",
  "Olympic events",
  "Olympics or World Cup hosts",
  "Painters/sculptors",
  "Parks",
  "Parts of the body",
  "People in uniform",
  "People who see you naked",
  "Personality traits",
  "Pets",
  "Phone apps",
  "Pizza toppings",
  "Places in Europe",
  "Places in the Middle East",
  "Places that fly flags",
  "Places to get news",
  "Places to hang out",
  "Places people have sex",
  "Places you can be naked",
  "Places you can get trapped",
  "Places you must wear a hat",
  "Places you're not allowed to go",
  "Plants",
  "Play titles",
  "Popular subjects on YouTube",
  "Private activities",
  "Product names",
  "Pro sports teams",
  "Rappers",
  "Reasons to call 911",
  "Reasons to call your ex",
  "Reasons to call your mother",
  "Reasons to change address",
  "Reasons to cut a vacation short",
  "Reasons to fly",
  "Reasons to get a babysitter",
  "Reasons to get a divorce",
  "Reasons to get a lawyer",
  "Reasons to get a loan",
  "Reasons to ghost a date",
  "Reasons to have a drink",
  "Reasons to line up",
  "Reasons to make a phone call",
  "Reasons to run away",
  "Reasons to see a therapist",
  "Reasons to slap someone",
  "Reasons to stay home",
  "Reasons to stay up all night",
  "Reasons to quit your job",
  "Reasons to tweet",
  "Reasons you crash your car",
  "Religious symbols",
  "Reptiles/amphibians",
  "Restaurants",
  "Rooms",
  "Sandwiches",
  "School subjects",
  "School supplies",
  "Science fiction terms",
  "Scientists",
  "Seafood",
  "Signage",
  "Slurs",
  "Software",
  "Something you're afraid of",
  "Something you keep hidden",
  "Song titles",
  "Sources of light or heat",
  "Spices & herbs",
  "Spicy foods",
  "Sports",
  "Sports equipment",
  "Spots to lose a phone",
  "States",
  "Statistics",
  "Stones",
  "Store names",
  "Street names",
  "Surnames",
  "Symptoms",
  "Team activities",
  "Tech companies",
  "Terms of endearment",
  "Terms of measurement",
  "Theatre terms",
  "Things at a circus",
  "Things at a construction site",
  "Things at a football game",
  "Things at a funeral",
  "Things at a gym",
  "Things at a museum",
  "Things at a parade",
  "Things at a wedding",
  "Things at Mount Everest",
  "Things at the beach",
  "Things found at a bar",
  "Things found in a couch",
  "Things found in a desk",
  "Things found in a hospital",
  "Things found in Abu Dhabi",
  "Things found in Cairo",
  "Things found in Paris",
  "Things found in Rio",
  "Things found in the ocean",
  "Things found in Tokyo",
  "Things found on a map",
  "Things found on social media",
  "Things in Antarctica",
  "Things in a backpack",
  "Things in a bathtub/shower",
  "Things in a cave",
  "Things in a courtroom",
  "Things in a grocery store",
  "Things in a mall",
  "Things in a medicine cabinet",
  "Things in a park",
  "Things in a souvenir shop",
  "Things in outer space",
  "Things in the desert",
  "Things in the sky",
  "Things made of fabric",
  "Things made of glass",
  "Things made of metal",
  "Things made of wood",
  "Things on a cruise ship",
  "Things on a deserted island",
  "Things on a golf course",
  "Things on a roof",
  "Things on a wall",
  "Things only rich people have",
  "Things on the moon",
  "Things on the ocean floor",
  "Things sold behind the counter",
  "Things that appreciate",
  "Things that are black",
  "Things that are blue",
  "Things that are cold",
  "Things that are flat",
  "Things that are furry/fuzzy",
  "Things that are hot",
  "Things that are illegal",
  "Things that are red",
  "Things that are round",
  "Things that are square",
  "Things that are squishy",
  "Things that are sticky",
  "Things that are triangular",
  "Things that are white",
  "Things that can kill you",
  "Things that cost about $10",
  "Things that cost about $100",
  "Things that cost about $1,000",
  "Things that depreciate",
  "Things that get you fired",
  "Things that go up and down",
  "Things that grow",
  "Things that have buttons",
  "Things that have spots",
  "Things that have stripes",
  "Things that have wheels",
  "Things that jump/bounce",
  "Things that make you smile",
  "Things that never move",
  "Things that shouldn't get wet",
  "Things that smell terrible",
  "Things that smell wonderful",
  "Things that spin",
  "Things that use a remote",
  "Things there's only one of",
  "Things to do at a party",
  "Things to do on a date",
  "Things to do while you wait",
  "Things tracked in spreadsheets",
  "Things with a dial",
  "Things with holes",
  "Things with tails",
  "Things you burn",
  "Things you buy for kids",
  "Things you buy secondhand",
  "Things you can be allergic to",
  "Things you can pawn",
  "Things you can't split",
  "Things you catch",
  "Things you climb",
  "Things you do at work",
  "Things you do every day",
  "Things you do with a baby",
  "Things you freeze",
  "Things you get from Amazon",
  "Things you get in the mail",
  "Things you get tickets for",
  "Things you hang up",
  "Things you hide from parents",
  "Things you invest in",
  "Things you keep forever",
  "Things you lend a friend",
  "Things you make",
  "Things you only do once",
  "Things you only get once",
  "Things you open",
  "Things you plug in",
  "Things you pull",
  "Things you recycle",
  "Things you replace",
  "Things you rub on yourself",
  "Things you see at a zoo",
  "Things you see with a telescope",
  "Things you shouldn't touch",
  "Things you shout",
  "Things you sit in/on",
  "Things you store items in",
  "Things you tear down",
  "Things you throw away",
  "Things you wear",
  "Things you whisper",
  "Things you write in a card",
  "Titles people can have",
  "Tools",
  "Topics in the news",
  "Tourist attractions",
  "Toys",
  "Trees",
  "Tropical locations",
  "TV shows",
  "TV stars",
  "Types of drink",
  "Types of weather",
  "Unbreakable things",
  "Underground things",
  "Unpotable liquids",
  "Vacation spots",
  "Valentine's Day words",
  "Vegetables",
  "Vehicles",
  "Video games",
  "Villains/monsters",
  "War terms",
  "Wars & conflicts",
  "Ways to communicate",
  "Ways to flirt",
  "Ways to get from here to there",
  "Ways to get rich",
  "Ways to give up",
  "Ways to help",
  "Ways to kill time",
  "Ways to say hello/goodbye",
  "Ways to say 'I love you'",
  "Ways to say yes or no",
  "Ways to say you're sorry",
  "Ways to spend retirement",
  "Ways to tell the time/date",
  "Weapons",
  "Websites",
  "Weekend activities",
  "Wikipedia entries",
  "Wild animals",
  "Wintry locations",
  "Wireless things",
  "Words ending in 'E'",
  "Words ending in 'L'",
  "Words ending in 'N'",
  "Words ending in 'R'",
  "Words ending in 'T'",
  "Words ending in 'Y'",
  "Words related to airports",
  "Words related to art",
  "Words related to body weight",
  "Words related to climate change",
  "Words related to coffee/tea",
  "Words related to exercise",
  "Words related to kindergarten",
  "Words related to fairy tales",
  "Words related to men",
  "Words related to money",
  "Words related to pirates",
  "Words related to religion",
  "Words related to romance",
  "Words related to slavery",
  "Words related to summer",
  "Words related to winter",
  "Words related to women",
  "Words with double letters",
  "Words with exactly 2 vowels",
  "Words with exactly 3 vowels",
  "Words with more than one meaning",
  "World leaders/politicians"
];

const LOCAL_CATEGORIES = {
  'Canada': [
    "Canadian celebrities",
    "Canadian towns/cities",
    "Things at a hockey game"
  ],
  'Jamaica': [
    "Caribbean foods",
    "Jamaican personalities",
    "Jamaican towns/cities",
    "Things at a cricket game",
    "Things at Jamaica Carnival",
    "Things found in Kingston",
    "Words from Jamaican patois"
  ],
  'UK': [
    "British celebrities",
    "British towns/cities",
    "Things found in London"
  ],
  'US': [
    "American cities",
    "American foods",
    "Thanksgiving items",
    "Things at a baseball game",
    "Things at a basketball game",
    "Things at Burning Man",
    "Things at the Superbowl",
    "Things found in New York",
    "Things in the Oval Office",
    "Things in Star Trek or Star Wars"
  ]
}
