// Gary
// ------------------------------------------------------------------------
// Copyright 2017 Keiran King

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// (https://www.apache.org/licenses/LICENSE-2.0)

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

// CONSTANTS
const STANDARD_CATEGORIES = [
  // List 1
  "A boy's name",
  "Jamaican towns/cities",
  "Things that are cold",
  "School supplies",
  "Pro sports teams",
  "Insects",
  "Breakfast foods",
  "Furniture",
  "TV shows",
  "Things found in the ocean",
  "Jamaican personalities",
  "Product names",
  // List 2
  "Vegetables",
  "States",
  "Things you throw away",
  "Occupations",
  "Appliances",
  "Cartoon characters",
  "Types of drink",
  "Musical groups",
  "Store names",
  "Things at a cricket game",
  "Trees",
  "Personality traits",
  // List 3
  "Articles of clothing",
  "Desserts",
  "Car parts",
  "Things found on a map",
  "Athletes",
  "4-letter words",
  "Items in a refrigerator",
  "Farm animals",
  "Street names",
  "Things at the beach",
  "Colors",
  "Tools",
  // List 4
  "Sports",
  "Song titles",
  "Parts of the body",
  "American foods",
  "Things you shout",
  "Birds",
  "A girl's name",
  "Ways to get from here to there",
  "Items in a kitchen",
  "Villains/monsters",
  "Flowers",
  "Things you replace",
  // List 5
  "Sandwiches",
  "Items in a catalog",
  "World leaders/politicians",
  "School subjects",
  "Excuses for being late",
  "Ice cream flavors",
  "Things that jump/bounce",
  "TV stars",
  "Things in a park",
  "Foreign cities",
  "Stones/gems",
  "Musical instruments",
  // List 6
  "Things that are sticky",
  "Awards/ceremonies",
  "Cars",
  "Spices/herbs",
  "Bad habits",
  "Cosmetics/toiletries",
  "Celebrities",
  "Cooking utensils",
  "Reptiles/amphibians",
  "Parks",
  "Leisure activities",
  "Things you're allergic to",
  // List 7
  "Fictional characters",
  "Menu items",
  "Magazines",
  "Capitals",
  "Kinds of candy",
  "Items you save up to buy",
  "Footwear",
  "Something you keep hidden",
  "Items in a suitcase",
  "Things with tails",
  "Sports equipment",
  "Crimes",
  // List 8
  "Nicknames",
  "Things in the sky",
  "Pizza toppings",
  "Colleges/universities",
  "Fish",
  "Countries",
  "Things that have spots",
  "Historical figures",
  "Something you're afraid of",
  "Terms of measurement",
  "Items in this room",
  "Book titles",
  // List 9
  "Restaurants",
  "Notorious people",
  "Fruits",
  "Things in a medicine cabinet",
  "Toys",
  "Household chores",
  "Bodies of water",
  "Authors",
  "Things at Jamaica Carnival",
  "Weapons",
  "Things that are round",
  "Words associated with exercise",
  // List 10
  "Heroes",
  "Gifts/presents",
  "Terms of endearment",
  "Kinds of dances",
  "Things that are black",
  "Vehicles",
  "Wintry locations",
  "College majors",
  "Dairy products",
  "Things in a souvenir shop",
  "Items in your purse/wallet",
  "World records",
  // List 11
  "Baby foods",
  "Famous duos and trios",
  "Things found in a desk",
  "Vacation spots",
  "Diseases",
  "Words associated with money",
  "Items in a vending machine",
  "Movie titles",
  "Games",
  "Things that you wear",
  "Liquors",
  "Things at a circus",
  // List 12
  "Famous females",
  "Medicines/drugs",
  "Things made of metal",
  "Hobbies",
  "People in uniform",
  "Things you plug in",
  "Animals",
  "Languages",
  "Names used in the Bible",
  "Junk food",
  "Things that grow",
  "Companies",
  // List 13
  "Video games",
  "Electronic gadgets",
  "Board games",
  "Things that use a remote",
  "Card games",
  "Internet lingo",
  "Offensive words",
  "Wireless things",
  "Computer parts",
  "Software",
  "Websites",
  "Game terms",
  // List 14
  "Things in a grocery store",
  "Reasons to quit your job",
  "Things that have stripes",
  "Tourist attractions",
  "Diet foods",
  "Things found in a hospital",
  "Food/drink that is green",
  "Weekend activities",
  "Acronyms",
  "Seafood",
  "Christmas songs",
  "Words ending in 'N'",
  // List 15
  "Words with double letters",
  "Children's books",
  "Things found at a bar",
  "Sports played indoors",
  "Names used in songs",
  "Foods you eat raw",
  "Places in Europe",
  "Olympic events",
  "Things you see at a zoo",
  "Math terms",
  "Animals in books or movies",
  "Things to do at a party",
  // List 16 (only 11 items)
  "Kinds of soup",
  "Things found in Kingston",
  "Things you get tickets for",
  "Things you do at work",
  "Foreign words used in English",
  "Things you shouldn't touch",
  "Spicy foods",
  "Things you make",
  "Places to hang out",
  "Animal noises",
  "Computer programs",
  // List 17 (only 11 items)
  "Honeymoon spots",
  "Things you buy for kids",
  "Things that can kill you",
  "Reasons to get a loan",
  "Words associated with winter",
  "Things to do on a date",
  "Historic events",
  "Things you store items in",
  "Things you do every day",
  "Things you get in the mail",
  "Things you sit in/on",
  // List 18 (only 11 items)
  "Reasons to make a phone call",
  "Types of weather",
  "Titles people can have",
  "Things that have buttons",
  "Items you take on a trip",
  "Things that have wheels",
  "Reasons to call 911",
  "Things that make you smile",
  "Ways to kill time",
  "Things that get you fired",
  "Holiday activities"
];

const GARY_CATEGORIES = [
  "Things at a basketball game",
  "Things at a football game",
  "Thanksgiving items",
  "Things that are triangular",
  "Things that are square",
  "Things that are white",
  "Things that are red",
  "Things that are blue",
  "Things that are squishy",
  "Things that are hot",
  "Things that are illegal",
  "Things made of fabric",
  "Things made of wood",
  "Things made of glass",
  "Things you do in private",
  "Things you recycle",
  "Microscopic things",
  "Things in outer space",
  "Things found on social media",
  "Things found in Tokyo",
  "Things found in Paris",
  "Things found in New York",
  "Things found in Rio",
  "Backyard items",
  "Things in a bathtub/shower",
  "Things in Antarctica",
  "Things on the moon",
  "Things only rich people have",
  "Famous people who aren't white",
  "Words associated with sex",
  "'Buzz' words",
  "Words associated with body weight",
  "Words associated with men",
  "Words associated with women",
  "Words associated with summer",
  "Words associated with religion",
  "War terms",
  "New Year's Eve words",
  "Valentine's Day words",
  "Words ending in 'T'",
  "Words ending in 'Y'",
  "Grammar terms",
  "Places you can have sex",
  "Places you can be naked",
  "Curse words",
  "3-letter words",
  "9-letter words",
  "Wild animals",
  "Tropical locations",
  "American cities",
  "Reasons to tweet",
  "Reasons to call your mother",
  "Reasons to call your ex",
  "Reasons to get a babysitter",
  "Reasons to get a divorce",
  "Reasons to have a drink",
  "Things at a wedding",
  "Things at a funeral",
  "Plants",
  "Pets",
  "Phone apps",
  "Movie stars",
  "Currencies",
  "Symptoms"
];
