// Gary
// Copyright 2017 Keiran King

// LICENSE --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// (https://www.apache.org/licenses/LICENSE-2.0)

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// CONSTANTS ------------------------------------------------------------------
const CATEGORIES = {
    "food": [
      "American foods",
      "Baby foods",
      "Breakfast foods",
      "Caribbean foods",
      "Dairy products",
      "Desserts",
      "Diet foods",
      "Food/drink that is green",
      "Foods you bake",
      "Foods you eat raw",
      "Fruits",
      "Ice cream flavors",
      "Items in a refrigerator",
      "Items in a vending machine",
      "Junk food",
      "Kinds of candy",
      "Kinds of soup",
      "Liquors",
      "Menu items",
      "Pizza toppings",
      "Sandwiches",
      "Seafood",
      "Spices/herbs",
      "Spicy foods",
      "Thanksgiving items",
      "Things found at a bar",
      "Things you freeze",
      "Things you're allergic to",
      "Types of drink",
      "Vegetables"
      ],
    "household": [
      "Appliances",
      "Articles of clothing",
      "Backyard items",
      "Bad habits",
      "Cooking utensils",
      "Cosmetics/toiletries",
      "Diseases",
      "Emotions",
      "Fetishes",
      "Footwear",
      "Furniture",
      "Gifts/presents",
      "Headwear",
      "Household chores",
      "Items in a catalog",
      "Items in a kitchen",
      "Items in this room",
      "Items in your purse/wallet",
      "Jewelry",
      "Medicines/drugs",
      "Personality traits",
      "Places you can be naked",
      "Places you can have sex",
      "Reasons to call 911",
      "Reasons to call your ex",
      "Reasons to call your mother",
      "Reasons to fly",
      "Reasons to get a babysitter",
      "Reasons to get a divorce",
      "Reasons to have a drink",
      "Reasons to make a phone call",
      "Something you're afraid of",
      "Something you keep hidden",
      "Symptoms",
      "Things at a funeral",
      "Things at a wedding",
      "Things in a bathtub/shower",
      "Things in a grocery store",
      "Things in a medicine cabinet",
      "Things on a wall",
      "Things that can kill you",
      "Things that use a remote",
      "Things that you wear",
      "Things you buy for kids",
      "Things you do every day",
      "Things you get in the mail",
      "Things you plug in",
      "Things you recycle",
      "Things you replace",
      "Things you sit in/on",
      "Things you store items in",
      "Things you throw away",
      "Tools",
      "Toys"
    ],
    "language": [
      "3-letter words",
      "4-letter words",
      "9-letter words",
      "Acronyms",
      "Curse words",
      "Foreign words used in English",
      "Game terms",
      "Grammar terms",
      "Internet lingo",
      "Legal terms",
      "Medical terms",
      "New Year's Eve words",
      "Offensive words",
      "Science fiction terms",
      "Terms of endearment",
      "Terms of measurement",
      "Theatre terms",
      "Valentine's Day words",
      "War terms",
      "Words associated with body weight",
      "Words associated with men",
      "Words associated with money",
      "Words associated with religion",
      "Words associated with sex",
      "Words associated with summer",
      "Words associated with winter",
      "Words associated with women",
      "Words ending in 'L'",
      "Words ending in 'N'",
      "Words ending in 'R'",
      "Words ending in 'T'",
      "Words ending in 'Y'",
      "Words with double letters",
      "Words without 'R', 'E', 'A', 'S', 'O', 'N'",
      ],
    "leisure and sport": [
      "Awards/ceremonies",
      "Board games",
      "Book titles",
      "Card games",
      "Cartoon characters",
      "Children's books",
      "Christmas songs",
      "Computer parts",
      "Computer programs",
      "Electronic gadgets",
      "Games",
      "Hobbies",
      "Holiday activities",
      "Kinds of dances",
      "Leisure activities",
      "Magazines",
      "Movie stars",
      "Movie titles",
      "Musical groups",
      "Musical instruments",
      "Olympic events",
      "Phone apps",
      "Places to hang out",
      "Play titles",
      "Private activities",
      "Pro sports teams",
      "Reasons to tweet",
      "Software",
      "Song titles",
      "Sports",
      "Sports equipment",
      "Sports played indoors",
      "Team activities",
      "Things at a basketball game",
      "Things at a cricket game",
      "Things at a football game",
      "Things found on social media",
      "Things in a souvenir shop",
      "Things on a golf course",
      "Things that make you smile",
      "Things to do at a party",
      "Things to do on a date",
      "Things you get tickets for",
      "TV shows",
      "TV stars",
      "Video games",
      "Ways to kill time",
      "Ways to communicate",
      "Websites",
      "Weekend activities",
      "Wireless things",
      "Words associated with exercise",
      "World records"
    ],
    "names": [
      "A boy's name",
      "A girl's name",
      "Athletes",
      "Authors",
      "Celebrities",
      "Famous criminals",
      "Famous duos and trios",
      "Famous females",
      "Famous people who aren't white",
      "Fictional characters",
      "Heroes",
      "Historical figures",
      "Jamaican personalities",
      "Names from Shakespeare",
      "Names used in songs",
      "Names used in the Bible",
      "Nicknames",
      "Notorious people",
      "Scientists",
      "Villains/monsters",
      "World leaders/politicians"
      ],
    "nature": [
      "Animal noises",
      "Animals",
      "Animals in books or movies",
      "Birds",
      "Farm animals",
      "Fish",
      "Flowers",
      "Gases",
      "Insects",
      "Microscopic things",
      "Parts of the body",
      "Pets",
      "Plants",
      "Reptiles/amphibians",
      "Stones/gems",
      "Things found in the ocean",
      "Things in a park",
      "Things in outer space",
      "Things in the desert",
      "Things in the sky",
      "Things on the moon",
      "Things that grow",
      "Things with tails",
      "Things you see at a zoo",
      "Things you see with a telescope",
      "Trees",
      "Types of weather",
      "Underground things",
      "Wild animals"
      ],
    "school, work, money": [
      "Airlines",
      "College majors",
      "Colleges/universities",
      "Companies",
      "Excuses for being late",
      "Items you save up to buy",
      "Math terms",
      "Occupations",
      "People in uniform",
      "Product names",
      "Reasons to get a loan",
      "Reasons to quit your job",
      "School subjects",
      "School supplies",
      "Things found in a desk",
      "Things in a courtroom",
      "Things only rich people have",
      "Things that get you fired",
      "Things you do at work",
      "Titles people can have"
      ],
    "travel": [
      "American cities",
      "Bodies of water",
      "Capitals",
      "Countries",
      "Currencies",
      "Foreign cities",
      "Historic events",
      "Honeymoon spots",
      "Items in a suitcase",
      "Items you take on a trip",
      "Jamaican towns/cities",
      "Languages",
      "Parks",
      "Places in Europe",
      "Restaurants",
      "States",
      "Store names",
      "Street names",
      "Things at Jamaica Carnival",
      "Things at the beach",
      "Things found in Kingston",
      "Things found in New York",
      "Things found in Paris",
      "Things found in Rio",
      "Things found in Tokyo",
      "Things found on a map",
      "Things in Antarctica",
      "Things on a cruise ship",
      "Tourist attractions",
      "Tropical locations",
      "Vacation spots",
      "Ways to get from here to there",
      "Wintry locations"
      ],
    "other": [
      "Car parts",
      "Cars",
      "Colors",
      "Crimes",
      "Fabrics",
      "Infrastructure",
      "Obsolete things",
      "Religious symbols",
      "Signs",
      "Things at a circus",
      "Things at a construction site",
      "Things at a parade",
      "Things found in a hospital",
      "Things made of fabric",
      "Things made of glass",
      "Things made of metal",
      "Things made of wood",
      "Things that are black",
      "Things that are blue",
      "Things that are cold",
      "Things that are furry/fuzzy",
      "Things that are hot",
      "Things that are illegal",
      "Things that are red",
      "Things that are round",
      "Things that are square",
      "Things that are squishy",
      "Things that are sticky",
      "Things that are triangular",
      "Things that are white",
      "Things that have buttons",
      "Things that have spots",
      "Things that have stripes",
      "Things that have wheels",
      "Things that jump/bounce",
      "Things that never move",
      "Things that spin",
      "Things with a dial",
      "Things you catch",
      "Things you make",
      "Things you open",
      "Things you pull",
      "Things you shouldn't touch",
      "Things you shout",
      "Things you whisper",
      "Unpotable liquids",
      "Vehicles",
      "Weapons"
      ]
}
